import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDay = new Date().getHours() >= 6 && new Date().getHours() < 18;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header isDay={isDay} />
        <main>{children}</main>
      </body>
    </html>
  );
}
